#!/usr/bin/python
import xlrd
import psycopg2

def inward():
    try:
    #filename = filedialog.askopenfile()
    #wb = xlrd.open_workbook(str(filename))
        wb = xlrd.open_workbook('Inward Register 2017-19\Inward Register 2017-19.xlsx')
        sheet = wb.sheet_by_name('Sheet1')
    #print(str(wb) + "" + str(sheet))
        for r in range(1, sheet.nrows):
                sourceidentifier = str(sheet.cell(r,0).value)
                sourcefilename = str(sheet.cell(r,1).value)
                glaccountcode = str(sheet.cell(r,2).value)
                profitcenter1 = str(sheet.cell(r,3).value)
                profitcenter2 = str(sheet.cell(r,4).value)
                palntcode = str(sheet.cell(r,5).value)
                returnperiod = str(sheet.cell(r,6).value)
                recipientgstin = str(sheet.cell(r,7).value)
                documenttype = str(sheet.cell(r,8).value)
                supplytype = str(sheet.cell(r,9).value)
                documentnumber = str(sheet.cell(r,10).value)
                documentdate = str(sheet.cell(r,11).value)
                originaldocumentnumber = str(sheet.cell(r,12).value)
                originaldocumentdate = str(sheet.cell(r,13).value)
                crdrpregst = str(sheet.cell(r,14).value)
                linenumber = str(sheet.cell(r,15).value)
                suppliergstin = str(sheet.cell(r,16).value)
                originalsuppliergstin = str(sheet.cell(r,17).value)
                suppliername = str(sheet.cell(r,18).value)
                suppliercode = str(sheet.cell(r,19).value)
                pos = str(sheet.cell(r,20).value)
                hsnorsac = str(sheet.cell(r,21).value)
                itemcode = str(sheet.cell(r,22).value)
                itemdescription = str(sheet.cell(r,23).value)
                categoryofitem = str(sheet.cell(r,24).value)
                unitofmeasurement = str(sheet.cell(r,25).value)
                quantity = str(sheet.cell(r,26).value)
                cessratespecific = str(sheet.cell(r,27).value)
                cessamountspecific = str(sheet.cell(r,28).value)
                invoicevalue = str(sheet.cell(r,29).value)
                reversechargeflag = str(sheet.cell(r,30).value)
                eligibilityindicator = str(sheet.cell(r,31).value)
                commonsupplyindicator = str(sheet.cell(r,32).value)
                purchasevouchernumber = str(sheet.cell(r,33).value)
                purchasevoucherdate = str(sheet.cell(r,34).value)
                paymentvouchernumber = str(sheet.cell(r,35).value)
                paymentdate = str(sheet.cell(r,36).value)
                contractnumber = str(sheet.cell(r,37).value)
                contractdate = str(sheet.cell(r,38).value)
                contractvalue = str(sheet.cell(r,39).value)
                userdefinedfiled1 = str(sheet.cell(r,40).value)
                userdefinedfield2 = str(sheet.cell(r,41).value)
                userdefinedfield3 = str(sheet.cell(r,42).value)

        try:
            conn = psycopg2.connect(user = "postgres",password = "rocker12", host = "127.0.0.1", port = "5433", database = "nova")
            cursor = conn.cursor()
            query = """INSERT INTO "INWARD"("SOURCEIDENTIFIER","SOURCEFILENAME","GLACCOUNTCODE","PROFITCENTRE1","PROFITCENTRE2","PLANTCODE","RETURNPERIOD","RECIPIENTGSTIN","DOCUMENTTYPE","SUPPLYTYPE","DOCUMENTNUMBER","DOCUMENTDATE","ORIGINALDOCUMENTNUMBER","ORIGINALDOCUMENTDATE","CRDRPREGST","LINENUMBER","SUPPLIERGSTIN","ORIGINALSUPPLIERGSTIN","SUPPLIERNAME","SUPPLIERCODE","POS","HSNORSAC","ITEMCODE","ITEMDESCRIPTION","CATEGORYOFITEM","UNITOFMEASUREMENT","QUANTITY","CESSRATESPECIFIC","CESSAMOUNTSPECIFIC","INVOICEVALUE","REVERSECHARGEFLAG","ELIGIBILITYINDICATOR","COMMONSUPPLYINDICATOR","PURCHASEVOUCHERNUMBER","PURCHASEVOUCHERDATE","PAYMENTVOUCHERNUMBER","PAYMENTDATE","CONTRACTNUMBER","CONTRACTDATE","CONTRACTVALUE","USERDEFINEDFIELD1","USERDEFINEDFIELD2","USERDEFINEDFIELD3") VALUES (%s, %s,%s,%s,%s,%s,%s, %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s,    %s)"""
            values = (sourceidentifier, sourcefilename, glaccountcode, profitcenter1, profitcenter2, palntcode, returnperiod, recipientgstin, documenttype, supplytype, documentnumber, documentdate, originaldocumentnumber, originaldocumentdate, crdrpregst, linenumber, suppliergstin, originalsuppliergstin, suppliername, suppliercode, pos, hsnorsac, itemcode, itemdescription, categoryofitem, unitofmeasurement, quantity, cessratespecific, cessamountspecific, invoicevalue, reversechargeflag, eligibilityindicator, commonsupplyindicator, purchasevouchernumber, purchasevoucherdate, paymentvouchernumber, paymentdate, contractnumber, contractdate, contractvalue, userdefinedfiled1, userdefinedfield2, userdefinedfield3)
            cursor.execute(query, values)
            cursor.close()
        except(Exception) as e:
            print(e)
        conn.commit()
        conn.close()
    except (Exception) as error:
        print(error)
